# coding: utf-8

"""
    IBANFIRST API documentation

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.payments_api import PaymentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentsApi(unittest.TestCase):
    """PaymentsApi unit test stubs"""

    def setUp(self):
        self.api = PaymentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_payments_id_confirm_put(self):
        """Test case for payments_id_confirm_put

        Confirm a payment  # noqa: E501
        """
        pass

    def test_payments_id_delete(self):
        """Test case for payments_id_delete

        Delete a payemt  # noqa: E501
        """
        pass

    def test_payments_id_get(self):
        """Test case for payments_id_get

        Get payment details  # noqa: E501
        """
        pass

    def test_payments_id_proof_of_transaction_put(self):
        """Test case for payments_id_proof_of_transaction_put

        Upload a proof of transaction for a payment  # noqa: E501
        """
        pass

    def test_payments_options_wallet_id_external_bank_account_id_get(self):
        """Test case for payments_options_wallet_id_external_bank_account_id_get

        Get payment options for a wallet and an external bank account  # noqa: E501
        """
        pass

    def test_payments_post(self):
        """Test case for payments_post

        Submit a payment  # noqa: E501
        """
        pass

    def test_payments_status_get(self):
        """Test case for payments_status_get

        Get payment list by status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
