# DockerFile
# required: Redis, Flask, python3, pandas, pyyaml,jsonschema, openpyxl, country-converter, configparser

FROM alpine:latest
LABEL maintainer="randy.bekalemd@gmail.com"
LABEL version="1.0"
#ARG
RUN git clone 
RUN chmod +x /entrypoint.sh
EXPOSE 8980
#ENV HEARTBEATSTEP=${HEARTBEATDEFAULT}
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]